name: dev_coinku
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.1.10
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  internet_connection_checker: 1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pinput: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 500
        - asset: assets/fonts/helvetica-light.ttf
          weight: 300
        - asset: assets/fonts/helvetica-bold.ttf
          weight: 700
